
services:
  api:
    container_name: django-social
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn CoreRoot.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
  
volumes:
  uploads_volume:
  postgres_data:
